apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: callmatic-3
  region: ap-south-1
  version: "1.33"

vpc:
  id: "vpc-06b196c8efd6b20b7"                # Replace with your existing VPC ID
  subnets:
    public:
      ap-south-1a:
        id: "subnet-0766e4d4237146050"       # Replace with your public subnet ID
      ap-south-1b:
        id: "subnet-0d2672ce1f8892850"
       # Optional: another subnet in a different AZ
    private:
      ap-south-1a:
        id: "subnet-059cec56c407bc3a6"
      ap-south-1b:
        id: "subnet-055af8883c13d682b"


iam:
  withOIDC: true                    # Enables OIDC provider for IRSA
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
    # Add more service accounts if needed
    # - metadata:
    #     name: external-dns
    #     namespace: kube-system
    #   wellKnownPolicies:
    #     externalDNS: true

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 4
    volumeSize: 20
    ssh:
      allow: true                # Enables SSH
      publicKeyName: deb  # Replace with the name of your EC2 key pair in AWS
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        cloudWatch: true
    tags:
      Name: callmatic-3
  # - name: ng-2
  #   instanceType: c5.2xlarge
  #   desiredCapacity: 2
  #   minSize: 0
  #   maxSize: 4
  #   volumeSize: 80
  #   ssh:
  #       allow: true
  #       publicKeyName: deb
  #   iam:
  #       withAddonPolicies:
  #           autoScaler: true
  #           ebs: true
  #           cloudWatch: true
  #   tags:
  #       Name: callmatic-3
extraAddons:
  - name: aws-lb-controller
  - name: cluster-autoscaler
  - name: kube-prometheus
  - name: kube-watch
    config:
      channels:
        - name: "slack"
          config:
           channel: ""
           token : ""
