apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- with .Values.resources }}
            resources:
              {{- toYaml . | nindent 12 }}
            {{- end }}
            envFrom:
              - configMapRef:
                name: {{ .Values.envConfigMap }}
          restartPolicy: {{ .Values.restartPolicy }}
      backoffLimit: {{ .Values.backoffLimit }}
      ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
